### ISSUE TITLE
Update to new dataframes interface

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#18] opened 2019-07-30 22:08 UTC
DataFrames has updated their interface completely, and now deprecation warnings are being thrown at the tests:
```
Test Summary: | Pass  Total
all the rest  |   10     10
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = #agents_data_complete#51(::Int64, ::Function, ::Array{Symbol,1}, ::Forest) at data_collector.jl:92
└ @ Agents C:\Users\datseris\.julia\packages\Agents\cBaCb\src\data_collector.jl:92
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = #agents_data_complete#51(::Int64, ::Function, ::Array{Symbol,1}, ::Forest) at data_collector.jl:94
└ @ Agents C:\Users\datseris\.julia\packages\Agents\cBaCb\src\data_collector.jl:94
Test Summary:  | Pass  Total
data_collector |    4      4
   Testing Agents tests passed
```
I'd recommend to fix them asap because in the next version of DataFrames those will be errors instead.

**Comment by def-mycroft** [comment] 2019-07-30 23:36
duplicate of #13

**Closed** 2019-07-31 07:19 UTC
